#!/bin/bash

function overwrite_and_link {
  ([ -f $1 ] | [ -L $1 ]) && rm $1
  ln -s $2 $1
}

# Creates a Symbolic link into the corresponding
# folders and files
overwrite_and_link ~/.vimrc $(pwd)/vimrc
overwrite_and_link ~/.tmux.conf $(pwd)/tmux.conf
overwrite_and_link ~/.vim $(pwd)/vim

